name: bus_attendance_app
description: A Flutter app for bus attendance using QR and Google Sheets

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  mobile_scanner: ^7.0.1
  flutter_secure_storage: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
